# db-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: library/postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "saleor"
            - name: POSTGRES_PASSWORD
              value: "saleor"
          volumeMounts:
            - name: saleor-db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: saleor-db
          persistentVolumeClaim:
            claimName: saleor-db-pvc
